server:
  port: 8765
  
spring:
  application:
    name: zuul-gateway1

zuul:
  #prefix: /api
  routes:
   product-catlog:
     path: /**
     service-id: product-catlog  
   user-service:
     path: /**
     #url: http://localhost:9092
     service-id: user-service
     
eureka:
  serviceUrl:
      defaultZone:http//localhost:8761/eureka/
